### ISSUE TITLE
why don't see rfc9381 vrf binding or implements?

### ISSUE THREAD

**Issue by ai-chen2050** [jedisct1/libsodium-sys-stable#16]
Why don't we see rfc9381 vrf binding or implements?
- because I need the vrf module in Rust, c version include vrf, 
- but in this version, I see nothing about vrf module.

**Comment by jedisct1** [comment]
VRF is only in the development code of libsodium. It's completely untested, is known to even not compile with the compilers, can be completely broken, and the API can change. 

This crate is for stable versions of libsodium.
