### ISSUE TITLE
Issues with compiling for android

### ISSUE THREAD

**Issue by ibnbatutah** [jedisct1/libsodium-sys-stable#17]
Hi,

Very new to rust. Was using flutter and flutter_rust_bridge to make an android app. Everything compiles except for libsodium-sys-stable. This is a dependency for another module that I am using. On running cargo ndk, I get this error:

--- stderr

thread 'main' panicked at C:\Users\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libsodium-sys-stable-1.21.4\build.rs:433:14:

called `Result::unwrap()` on an `Err` value: Os { code: 10060, kind: TimedOut, message: "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." }

Not sure on how to proceed. When I target windows, no issue. i.e.

cargo ndk -t x86_64 build - fails

cargo build - works okay

**Comment by ibnbatutah** [comment]
Just to add, might be similar to [Issue#14](https://github.com/jedisct1/libsodium-sys-stable/issues/14) as I am using a windows pc. Tried a cargo clean and now its failing on windows build too.

**Comment by jedisct1** [comment]
Try version 1.22.1 maybe.

**Comment by ibnbatutah** [comment]
Finally shifted to WSL for development and do not have any issues now.
