### ISSUE TITLE
Disavow deprecated sodiumoxide?

### ISSUE THREAD

**Issue by neonphog** [jedisct1/libsodium-sys-stable#8]
@jedisct1 - Now that [sodiumoxide](https://github.com/sodiumoxide/sodiumoxide) has been deprecated, I'm looking for a maintained, up-to-date libsodium sys integration such as this to back [sodoken](https://crates.io/crates/sodoken).

Do you intend to keep maintaining this? If so, would it make sense to remove the references to sodiumoxide in the repo?

**Comment by jedisct1** [comment]
I'm using it for [encrypted-dns-server](https://github.com/DNSCrypt/encrypted-dns-server), so yes, I'm intending to keep maintaining it.

**Comment by pinkforest** [comment]
Hey Frank just wanted to say thanks for forking the sys! :crab: 

I'm gonna be migrating probably a few in and we recommended as alternatives
